config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :roommates

  resources :chores

 root 'chores#index'

end

app/models/chore.rb
class Chore < ActiveRecord::Base
  belongs_to :roommate
end

app/models/roommate.rb
class Roommate < ActiveRecord::Base
  has_many :chores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: [:show, :edit, :update, :destroy]

  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
  end

  # GET /chores/new
  def new
    @chore = Chore.new
  end

  # GET /chores/1/edit
  def edit
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = Chore.new(chore_params)

    respond_to do |format|
      if @chore.save
        format.html { redirect_to @chore, notice: 'Chore was successfully created.' }
        format.json { render :show, status: :created, location: @chore }
      else
        format.html { render :new }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1
  # PATCH/PUT /chores/1.json
  def update
    respond_to do |format|
      if @chore.update(chore_params)
        format.html { redirect_to @chore, notice: 'Chore was successfully updated.' }
        format.json { render :show, status: :ok, location: @chore }
      else
        format.html { render :edit }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore.destroy
    respond_to do |format|
      format.html { redirect_to chores_url, notice: 'Chore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore
      @chore = Chore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chore_params
      params.require(:chore).permit(:title, :description, :image_url)
    end
end

app/controllers/roommates_controller.rb
class RoommatesController < ApplicationController
  before_action :set_roommate, only: [:show, :edit, :update, :destroy]

  # GET /roommates
  # GET /roommates.json
  def index
    @roommates = Roommate.all
  end

  # GET /roommates/1
  # GET /roommates/1.json
  def show
  end

  # GET /roommates/new
  def new
    @roommate = Roommate.new
  end

  # GET /roommates/1/edit
  def edit
  end

  # POST /roommates
  # POST /roommates.json
  def create
    @roommate = Roommate.new(roommate_params)

    respond_to do |format|
      if @roommate.save
        format.html { redirect_to @roommate, notice: 'Roommate was successfully created.' }
        format.json { render :show, status: :created, location: @roommate }
      else
        format.html { render :new }
        format.json { render json: @roommate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roommates/1
  # PATCH/PUT /roommates/1.json
  def update
    respond_to do |format|
      if @roommate.update(roommate_params)
        format.html { redirect_to @roommate, notice: 'Roommate was successfully updated.' }
        format.json { render :show, status: :ok, location: @roommate }
      else
        format.html { render :edit }
        format.json { render json: @roommate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roommates/1
  # DELETE /roommates/1.json
  def destroy
    @roommate.destroy
    respond_to do |format|
      format.html { redirect_to roommates_url, notice: 'Roommate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roommate
      @roommate = Roommate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roommate_params
      params.require(:roommate).permit(:name, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/roommates_helper.rb
module RoommatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing Chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chores</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Roommate</th>
      <th colspan="3"></th>
      <th>Completed</th>
    </tr>
  </thead>

  <tbody>
    <% @chores.each do |chore| %>
      <tr>
        <td><%= chore.title %></td>
        <td><%= chore.description %></td>
        <td><%= chore.roommate.name %></td>
        <td><%= link_to 'Show', chore %></td>
        <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
        <td><%= link_to 'Destroy', chore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chore', new_chore_path %>

app/views/chores/new.html.erb
<h1>New Chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chore.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @chore.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @chore.image_url %>
</p>

<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apt3957</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/roommates/_form.html.erb
<%= form_for(@roommate) do |f| %>
  <% if @roommate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roommate.errors.count, "error") %> prohibited this roommate from being saved:</h2>

      <ul>
      <% @roommate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roommates/edit.html.erb
<h1>Editing Roommate</h1>

<%= render 'form' %>

<%= link_to 'Show', @roommate %> |
<%= link_to 'Back', roommates_path %>

app/views/roommates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Roommates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roommates.each do |roommate| %>
      <tr>
        <td><%= roommate.name %></td>
        <td><%= roommate.description %></td>
        <td><%= link_to 'Show', roommate %></td>
        <td><%= link_to 'Edit', edit_roommate_path(roommate) %></td>
        <td><%= link_to 'Destroy', roommate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roommate', new_roommate_path %>

app/views/roommates/new.html.erb
<h1>New Roommate</h1>

<%= render 'form' %>

<%= link_to 'Back', roommates_path %>

app/views/roommates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @roommate.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @roommate.description %>
</p>

<%= link_to 'Edit', edit_roommate_path(@roommate) %> |
<%= link_to 'Back', roommates_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<h1>Welcome to Apt. 3957!</h1>





<footer>Find me in app/views/welcome/index.html.erb</footer>